const fs = require('fs');
const path = require('path');
const assert = require('assert');

const sitePath = path.join(__dirname, '..', 'index.html');
const html = fs.readFileSync(sitePath, 'utf8');

function contains(text) {
  assert(
    html.includes(text),
    `Expected index.html to include: ${text}`
  );
}

function excludes(text) {
  assert(
    !html.includes(text),
    `Expected index.html not to include: ${text}`
  );
}

contains('<title>Lingxing Yao | Mathematics</title>');
contains('Associate Professor');
contains('Department of Mathematics');
contains('The University of Akron');
contains('Mathematical modeling');
contains('Cell motility');
contains('Polyelectrolyte hydrogels');
contains('Numerical algorithms');
contains('Selected Publications');
contains('Introduction to ODE');
contains('lyao@uakron.edu');
contains('330-972-7402');
contains('CAS 256');

excludes('Evelyn Reed');
excludes('Generated by Gemini');
excludes('placehold.co');
excludes('[your-email]');

console.log('Site content checks passed.');
